@BASE_URL=http://localhost:3000/api
@USER_ID=655b16efb33bbc4838928d5a

###

GET {{BASE_URL}}/users HTTP/1.1

###

POST {{BASE_URL}}/users HTTP/1.1
Content-Type: application/json

{
  "username": "johndoe",
  "email": "johndoe@mail.com",
  "password": "12346"
}

###

GET {{BASE_URL}}/users/{{USER_ID}} HTTP/1.1